[tool.poetry]
name = "playwright-python"
version = "0.1.0"
description = ""
authors = ["noamolat-fs <noamolat@fullscale.ph>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
ruff = "^0.3.4"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
